### PR TITLE
Correction of rebuild on comment on wrong pipeline

### LINKED ISSUE #256: MR comment triggers rebuild on wrong project
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
```
Jenkins: 2.375.1
OS: Linux - 4.15.0-200-generic
---
ace-editor:1.1
ant:481.v7b_09e538fcca
antisamy-markup-formatter:155.v795fb_8702324
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
audit-trail:3.11
authentication-tokens:1.4
aws-java-sdk-ec2:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-minimal:1.12.287-357.vf82d85a_6eefd
basic-branch-build-strategies:71.vc1421f89888e
blueocean:1.25.8
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.8
blueocean-commons:1.25.8
blueocean-config:1.25.8
blueocean-core-js:1.25.8
blueocean-dashboard:1.25.8
blueocean-display-url:2.4.1
blueocean-events:1.25.8
blueocean-git-pipeline:1.25.8
blueocean-github-pipeline:1.25.8
blueocean-i18n:1.25.8
blueocean-jira:1.25.8
blueocean-jwt:1.25.8
blueocean-personalization:1.25.8
blueocean-pipeline-api-impl:1.25.8
blueocean-pipeline-editor:1.25.8
blueocean-pipeline-scm-api:1.25.8
blueocean-rest:1.25.8
blueocean-rest-impl:1.25.8
blueocean-web:1.25.8
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.1-3
bouncycastle-api:2.26
branch-api:2.1051.v9985666b_f6cc
build-history-manager:1.6.0
build-notifications:1.5.0
build-publisher:1.22
build-timeout:1.25
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.8.0
cloudbees-bitbucket-branch-source:791.vb_eea_a_476405b
cloudbees-folder:6.800.v71307ca_b_986b
command-launcher:90.v669d7ccb_7c31
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-27.vb_fa_3896786a_7
conditional-buildstep:1.4.2
configuration-as-code:1569.vb_72405b_80249
copyartifact:1.48
credentials:1214.v1de940103927
credentials-binding:523.vd859a_4b_122e6
data-tables-api:1.12.1-4
display-url-api:2.3.6
docker-commons:1.21
docker-workflow:563.vd5d2e5c4007f
durable-task:503.v57154d18d478
echarts-api:5.4.0-1
external-monitor-job:203.v683c09d993b_9
favorite:2.4.1
font-awesome-api:6.2.1-1
git:4.14.1
git-client:3.13.0
git-server:99.va_0826a_b_cdfa_d
github:1.36.0
github-api:1.303-400.v35c2d8258028
github-branch-source:1696.v3a_7603564d04
github-oauth:0.39
github-pr-comment-build:86.v23ae6d00ab99
gitlab-api:5.0.1-78.v47a_45b_9f78b_7
gitlab-branch-source:643.vdc12a_4a_06434
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.31
instance-identity:142.v04572ca_5b_265
instant-messaging:2.651.v8a_fc721a_5fe8
ionicons-api:31.v4757b_6987003
jackson2-api:2.14.1-313.v504cdd45c18b
jakarta-activation-api:2.0.1-2
jakarta-mail-api:2.0.1-2
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-5
javax-mail-api:1.6.2-8
jaxb:2.3.7-1
jdk-tool:63.v62d2fd4b_4793
jenkins-design-language:1.25.8
jersey2-api:2.37-1
jira:3.8
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.16-1
job-dsl:1.81
jobConfigHistory:1191.v168c8c2b_956a
jquery-detached:1.2.1
jquery3-api:3.6.1-2
jsch:0.1.55.61.va_e9ee26616e7
junit:1166.va_436e268e972
ldap:2.12
lockable-resources:1069.v726298f53f8c
mailer:438.v02c7f0a_12fa_4
mapdb-api:1.0.9-28.vf251ce40855d
matrix-auth:3.1.5
matrix-project:785.v06b_7f47b_c631
maven-plugin:3.20
metrics:4.2.13-420.vea_2f17932dd6
mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
momentjs:1.1.1
notification:1.15
okhttp-api:4.9.3-108.v0feda04578cf
pam-auth:1.10
parameterized-trigger:2.45
pipeline-build-step:2.18
pipeline-github-lib:38.v445716ea_edda_
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:621.vb_44ce045b_582
pipeline-input-step:466.v6d0a_5df34f81
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-rest-api:2.28
pipeline-stage-step:296.v5f6908f017a_5
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
pipeline-stage-view:2.28
plain-credentials:139.ved2b_9cf7587b
plugin-util-api:2.20.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
pubsub-light:1.17
purge-build-queue-plugin:88.v23b_97b_f2c7a_d
purge-job-history:1.6
resource-disposer:0.20
run-condition:1.5
scm-api:621.vda_a_b_055e58f7
scoring-load-balancer:1.0.1
script-security:1218.v39ca_7f7ed0a_c
simple-theme-plugin:136.v23a_15f86c53d
snakeyaml-api:1.33-90.v80dcb_3814d35
sse-gateway:1.26
ssh-credentials:305.v8f4381501156
ssh-slaves:2.854.v7fd446b_337c9
sshd:3.270.vb_a_e71e64c287
structs:324.va_f5d6774f3a_d
telegram-notifications:1.4.0
thinBackup:1.14
throttle-concurrents:2.10
timestamper:1.21
token-macro:321.vd7cc1f2a_52c8
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
view-job-filters:2.3
windows-slaves:1.8.1
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1200.v8005c684b_a_c6
workflow-basic-steps:994.vd57e3ca_46d24
workflow-cps:3536.vb_8a_6628079d5
workflow-cps-global-lib:609.vd95673f149b_b
workflow-durable-task-step:1217.v38306d8fa_b_5c
workflow-job:1254.v3f64639b_11dd
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
ws-cleanup:0.43
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 18.04

### Reproduction steps

Have 2 projects having the same "branch" (example MR-2) name in the same subproject

### Expected Results

rebuilds correct project

### Actual Results

rebuilds wrong project

### Anything else?

Logs:

```
Dec 05, 2022 11:19:53 PM INFO io.jenkins.plugins.gitlabbranchsource.GitLabMergeRequestCommentTrigger isMatch

Triggered build for UBportsCore/lomiri-thumbnailer/MR-12 due to MR comment on ubports/development/core/packaging/bluebinder

```

### PR DESCRIPTION
**Pull request by Turiok**
filtered jenkins jobs with SCMSource of the payload on comment trigger

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

close #256 

Be careful with this PR. There isn't a lot of code but the fix seems very important I think.
If several people can test it, It'll be appreciated.

In GitLabMergeRequestCommentTrigger class to find which job build depending on the payload information of the webhook. There isn't link between GItlab Project Id and Jenkins jobs. I add a if between these 2 objects with the job parent Item.

```
# Verify the projectId is asked
if (gitLabSCMSource.getProjectId() == getPayload().getMergeRequest().getTargetProjectId()
    && isTrustedMember(gitLabSCMSource, sourceContext.getOnlyTrustedMembersCanTrigger())) {
    # search in all jobs of the same owner.  And there isn't another verification with the payload
    for (Job<?, ?> job : owner.getAllJobs()) {
```

To reproduce the previous problem : 
- Create 2 Gitlab projects with the same Owner.
- Each project with a MR with the same branch name.
- Configure webhook settings for Jenkins in GItlab project settings and enable comment event
- In Jenkins create 2 multibranches pipelines and enable comment rebuild trait
- On first MR add the comment to launch a webhook.
- Verify the right pipeline is executed
- On second MR add the comment to launch a webhook.
- The pipeline executed is the same that the first one.

Be careful to test it with any other pipeline executed.

### CODE REVIEW

File: src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabMergeRequestCommentTrigger.java [hunk 1]
```diff
@@ -56,29 +58,33 @@ public void isMatch() {
                         if (gitLabSCMSource.getProjectId() == getPayload().getMergeRequest().getTargetProjectId()
                                 && isTrustedMember(gitLabSCMSource, sourceContext.getOnlyTrustedMembersCanTrigger())) {
                             for (Job<?, ?> job : owner.getAllJobs()) {
```
Comment (Turiok) [inline src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabMergeRequestCommentTrigger.java:60]: With this for, we loop to all jobs. Even out of the projectId. And there isn't more check after with the payload

File: src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabMergeRequestCommentTrigger.java [hunk 2]
```diff
@@ -56,29 +58,33 @@ public void isMatch() {
...
-                                                        job.getFullName(),
-                                                        getPayload().getProject().getPathWithNamespace()
-                                                });
-                                    } else {
-                                        LOGGER.log(Level.INFO,
-                                                "MR comment does not match the trigger build string ({0}) for {1}",
-                                                new Object[] { expectedCommentBody, job.getFullName() });
+                                if (MultiBranchProject.class.isAssignableFrom(job.getParent().getClass()) ) {
+                                    MultiBranchProject parentJob = (MultiBranchProject) job.getParent();
+                                    if (parentJob.getSCMSource(gitLabSCMSource.getId()) == gitLabSCMSource
```
Comment (Turiok) [inline src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabMergeRequestCommentTrigger.java:63]: I try to check the link between the source of the payload and the job in the for.

I don't know if there is a better solution

**Review by jetersen — APPROVED** [review]
Seems safer way of handling it.
