### PR TITLE
Migrate Webhook secret to String Credential and fix issue with persistent for JCasC

### LINKED ISSUE #162: Webhook secret is deleted by JCasC on every restart
### Version report

Jenkins and plugins versions report:

```
Jenkins LTS 2.303.2
GitLab branch source plugin 1.5.9
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Linux
```

### Reproduction steps

- Define GitLab branch source config in JCasC (Jenkins configuration as code), without setting the webhook secret (since the JCasC config is stored in a public Git repo)
- Set webhook secret in the global GitLab branch source config
- Restart Jenkins instance

### Results

Expected result:

Since the webhook secret is not set in JCasC, it should not be reset/deleted.

Actual result:

Webhook secret is reset/deleted.

Side note:
Not setting a webhook secret is no longer an option due to #106.

Proposed changes:
* Do not reset/delete a value of a config field if it's not set in JCasC.
* Allow to store webhook secret in Jenkins credentials so it's not exposed in plain text JCasC.

### PR DESCRIPTION
**Pull request by fredg02**
Use Jenkins credentials for webhook secret.

fixes #162

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by fredg02** [comment]
@jetersen is there anything I can do to get this merged in the foreseeable future? This affects a lot of our projects hosted at gitlab.eclipse.org.

**Comment by fredg02** [comment]
@mifitous can you take a look at this pull request? It would help us a lot if this can be fixed soon.

File: src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java [hunk 1]
```diff
@@ -120,9 +122,17 @@ public class GitLabServer extends AbstractDescribableImpl<GitLabServer> {
     private String hooksRootUrl;
 
     /**
-     * The secret token used while setting up hook url in the GitLab server
+     * The credentials id of the secret token used while setting up hook url in the GitLab server
      */
-    private Secret secretToken;
```
Comment (jetersen) [inline src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:125]: This should be marked `transiant` and use a `readResolve` to transfer `secretToken` into the credentials id.

https://www.jenkins.io/doc/developer/persistence/backward-compatibility/

Otherwise, you would brick everyone's setup when upgrading to this plugin version.

You can see how this is implemented here:
https://github.com/jenkinsci/email-ext-plugin/blob/daea4f4780913aa0068ee842368c5f42bdfcbb68/src/main/java/hudson/plugins/emailext/MailAccount.java#L263-L268

File: src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java [hunk 2]
```diff
@@ -120,9 +122,17 @@ public class GitLabServer extends AbstractDescribableImpl<GitLabServer> {
...
+    @NonNull
+    private String secretTokenCredentialsId;
```
Comment (jetersen) [inline src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:128]: Could consider calling it `credentialsId` but can also leave it as is.

**Review by jetersen — CHANGES_REQUESTED** [review]

File: src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java (hunk 2 above)
Comment (fredg02) [reply src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:128]: `credentialsId` is already used for the PAT credentials ID => https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/69d3ba371450a9d0ff28fb917ffa90631f5a7f94/src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java#L111-L116 

So I had to pick a different name, but I'm open for better names.

File: src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java (hunk 1 above)
Comment (fredg02) [reply src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:125]: Good point. I will take a look at this.

File: src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java (hunk 2 above)
Comment (jetersen) [reply src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:128]: how about `webhookSecretCredentialsId` 🤔 making it descriptive? 😅

File: src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java [hunk 3]
```diff
@@ -271,15 +282,47 @@ public String getHooksRootUrl() {
     }
 
     @DataBoundSetter
-    public void setSecretToken(Secret token) {
```
Comment (jetersen) [inline src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:274]: Hmm this is breaking binary compatibility and JCasC compatibility. I believe the proper way is to retain the getter and setter and make them use the credential.

Not sure if the `setSecretToken` should retain the `@DataBoundSetter` migration is always hard 😰

File: src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java (hunk 2 above)
Comment (fredg02) [reply src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:128]: :+1:

**Comment by fredg02** [comment]
I've kept the getter and setter for now. 

I've manually tested the migrate method with the following scenarios:
- migration of webhook secret to Jenkins credential
  - Jenkins credential is created correctly ✅
  - content of new Jenkins credential == old webhook secret ✅
- credential (with a different name) already exists
  - worked (existing credential was selected in the GitLab Branch Source config) ✅
- dev version is installed without an existing config
  - no errors ✅

Not sure if it's necessary to create mock tests for the migrate method.

File: src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java [hunk 4]
```diff
@@ -281,46 +293,51 @@ public String getHooksRootUrl() {
         return Util.ensureEndsWith(Util.fixEmptyAndTrim(hooksRootUrl), "/");
     }
 
+    @DataBoundSetter @Deprecated
```
[the remark this answers is not in the document]
Comment (fredg02) [reply src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:296]: Ok. I'll test it.

[the remark this answers is not in the document]
Comment (fredg02) [reply src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:296]: AFAICT `secretToken` is not shown in JCasC here: http://localhost:8080/manage/configuration-as-code/reference after applying the changes in this PR, or did you mean a different place?

I've tested the three scenarios above with the removed `@DataBoundSetter` annotation and did not find any difference.

In the example you have given (https://github.com/jenkinsci/email-ext-plugin/blob/daea4f4780913aa0068ee842368c5f42bdfcbb68/src/main/java/hudson/plugins/emailext/MailAccount.java#L263-L268), the `@DataBoundSetter` annotations were also still set.

Let me know if you want to keep or remove the ` @DataBoundSetter` for `secretToken`.

[the remark this answers is not in the document]
Comment (jetersen) [reply src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java:296]: let's keep it, I remember recalling JCasC ignoring deprecated values but allows for old YAML fields to load correctly.

**Comment by jetersen** [comment]
@fredg02 Mind resolving the merge conflict? :)

**Comment by fredg02** [comment]
> @fredg02 Mind resolving the merge conflict? :)

Done. I did a rebase and added a commit to fix indentation.

**Comment by fredg02** [comment]
@jetersen please let me know if anything is required from my side to push this forward.

**Comment by fredg02** [comment]
@jetersen friendly ping

**Review by jetersen — APPROVED** [review]

**Comment by jetersen** [comment]
Fixed in https://github.com/jenkinsci/gitlab-branch-source-plugin/releases/tag/646.vb_9560d64b_69f

**Comment by fredg02** [comment]
Thanks for all your help! :pray:

**Comment by bguerin** [comment]
Well ... with these changes, if I configure a token, I got
https://github.com/jenkinsci/gitlab-branch-source-plugin/issues/286
which is because this line
https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/master/src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java#L377

and if I do not configure token, I got a NullPointerException here (` str2`  is null)
https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/master/src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabHookCreator.java#L231

So, I am stuck ...

**Comment by jetersen** [comment]
@bguerin PRs are welcome

**Comment by fredg02** [comment]
Yeah, I tried to copy that part, but I'm not sure how I can provide the `context` as parameter.

**Comment by jetersen** [comment]
Either source.GetOwner() or observer.getContext() it is used in other places.

Just check for usage on [`getCredentials`](https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/b9560d64b69f2e2b3ecc334a9f4ac463b0c26013/src/main/java/io/jenkins/plugins/gitlabserverconfig/servers/GitLabServer.java#L278)

**Comment by fredg02** [comment]
Alright. I'll try to get this fixed in a timely manner. Sorry about the regression my PR introduced.

**Comment by fredg02** [comment]
I've tried to check how other plugins handle this (e.g. the GitHub plugin). It looks like there is no permissions check in https://github.com/jenkinsci/github-plugin/blob/master/src/main/java/org/jenkinsci/plugins/github/config/GitHubServerConfig.java#L288.

**Comment by jetersen** [comment]
Feel free to submit a PR :)

**Comment by MarkEWaite** [comment]
@fredg02 I believe that the regression has also been reported as [JENKINS-70785](https://issues.jenkins.io/browse/JENKINS-70785).  Are you willing to investigate a fix for that regression or is that an intentional case and the user needs to perform some specific upgrade step to change from `secretToken` to another way of defining the credential in configuration as code?
